name: Heroku Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{github.repository_owner}}-${{github.event.repository.name}}
          heroku_email: "zachary.bell.me@gmail.com"
        env:
          HD_OPEN_WEATHER_API_KEY: ${{secrets.OPEN_WEATHER_API_KEY}}